### ISSUE TITLE
Setting "initialValue" causes year to be reset to 1970 when tapping on form field.

### ISSUE THREAD

**Issue by 3to1null** [jifalops/datetime_picker_formfield#33]
As the title says, if I set 'initialValue' to any DateTime object, it resets the year of said DateTime object to 1970, as soon as the formfield is tapped. It does display the correct date before the field is tapped. 

The DateTimePicker is opened on the changed value, and the onChanged listeners also gets the 'update'.

My code:
```
DateTimePickerFormField(
            format: DateFormat("EEEE',' d MMMM"),
            initialDate: initialDate,
            initialValue: initialDate,
            inputType: InputType.date,
            editable: false,
            decoration: InputDecoration(
              contentPadding: EdgeInsets.all(2.0),
              labelText: 'Datum',
              icon: Icon(Icons.date_range)
            ),
            onChanged: (DateTime value){
              if(value != null && value.isAfter(DateTime.now().subtract(Duration(days: 3)))){
                formData["date"] = DateFormat("yyyy-MM-dd").format(value);
              }
            },
          ),
```

If I remove `initialValue: initialDate` everything works fine. (Except for the fact that there is no initialValue, obviously).

**Comment by vishnyakov-aleks** [comment]
same issue

**Comment by jifalops** [comment]
Can one of you see if you still have the issue on v0.3.0?

**Comment by VedavyasBhat** [comment]
Yes, the issue still persists, because the date passed to `onChange` is actually read from the text field, so if that field's formatting does not have year in it. it will become the unix default. My temporary fix for this is to change your date format to include year. I have opened an issue for the same here: https://github.com/jifalops/datetime_picker_formfield/issues/64
